name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci, lint, test and build
      run: |
        npm ci
        npm run lint
        npm test -- praparat --no-watch --no-progress --browsers=ChromeHeadlessCI
        npm run build -- praparat
        npm run build -- demo-app --prod
        cp ./README.md ./dist/praparat
        cp ./LICENSE ./dist/praparat
      env:
        CI: true
    - name: publish
      run: |
        npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: praparat-artifact
        path: dist/praparat
